version: "3"

tasks:
  docker:up:
    desc: Start Docker containers (DB etc.)
    cmds:
      - docker-compose up -d

  docker:down:
    desc: Stop Docker containers and remove volumes
    cmds:
      - docker-compose down -v

  test:
    desc: Run all tests
    cmds:
      - go test ./... -v

  lint:
    desc: Run golangci-lint
    cmds:
      - go install mvdan.cc/gofumpt@latest
      - gofumpt -w .
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint run ./... --timeout=5m

  build:
    desc: Build the application
    cmds:
      - go build -o bin/app ./main.go

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./bin/app

  # Event Store Migrations
  migrate:eventstore:up:
    desc: Run event store migrations up
    cmds:
      - |
        goose -dir internal/infrastructure/database/eventstore/migration -table goose_db_version_eventstore mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4" up

  migrate:eventstore:down:
    desc: Run event store migrations down
    cmds:
      - |
        goose -dir internal/infrastructure/database/eventstore/migration -table goose_db_version_eventstore mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4" down

  migrate:readmodel:up:
    desc: Run read model migrations up
    cmds:
      - |
        goose -dir internal/infrastructure/database/readmodel/migrations -table goose_db_version_readmodel mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4" up

  migrate:readmodel:down:
    desc: Run read model migrations down
    cmds:
      - |
        goose -dir internal/infrastructure/database/readmodel/migrations -table goose_db_version_readmodel mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4" down

  # Test Database Migrations
  migrate:test:eventstore:up:
    desc: Run event store migrations up for test database
    cmds:
      - |
        goose -dir internal/infrastructure/database/eventstore/migration -table goose_db_version_eventstore mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_TEST_DATABASE}?parseTime=true&charset=utf8mb4" up

  migrate:test:readmodel:up:
    desc: Run read model migrations up for test database
    cmds:
      - |
        goose -dir internal/infrastructure/database/readmodel/migrations -table goose_db_version_readmodel mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_TEST_DATABASE}?parseTime=true&charset=utf8mb4" up

  migrate:test:eventstore:down:
    desc: Run event store migrations down for test database
    cmds:
      - |
        goose -dir internal/infrastructure/database/eventstore/migration -table goose_db_version_eventstore mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_TEST_DATABASE}?parseTime=true&charset=utf8mb4" down

  migrate:test:readmodel:down:
    desc: Run read model migrations down for test database
    cmds:
      - |
        goose -dir internal/infrastructure/database/readmodel/migrations -table goose_db_version_readmodel mysql \
        "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_TEST_DATABASE}?parseTime=true&charset=utf8mb4" down

  migrate:all:up:
    desc: Run all migrations up (main and test databases for both eventstore and readmodel)
    cmds:
      - task: migrate:eventstore:up
      - task: migrate:readmodel:up
      - task: migrate:test:eventstore:up
      - task: migrate:test:readmodel:up

  migrate:all:down:
    desc: Run all migrations down (main and test databases for both eventstore and readmodel)
    cmds:
      - task: migrate:test:readmodel:down
      - task: migrate:test:eventstore:down
      - task: migrate:readmodel:down
      - task: migrate:eventstore:down

  db:setup:
    desc: Setup both main and test databases with migrations
    cmds:
      - task: migrate:up
      - task: migrate:test:up